# Common configuration for all services
x-common: &common
  env_file:
    - .env
  volumes:
      - /dev/shm:/dev/shm
      - ./fastrtps.xml:/fastrtps.xml
  network_mode: host
  restart: unless-stopped


services:  
  ros2-bridge-12:
    <<: *common
    build: .
    container_name: ros2_bridge_12
    environment:
      - ROS_DOMAIN_ID=12                     # Set Domain ID to 12
    # RUN web bridge
    command: bash -c "source /opt/ros/humble/setup.bash &&
                        ros2 launch rosbridge_server rosbridge_websocket_launch.xml port:=9012"

  web-host:
    image: nginx:alpine
    container_name: web_host
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "8080:80"
    restart: unless-stopped
  




# make an image to run dds discovery server
  ros2-discovery:
    <<: *common
    image: ros:humble-ros-base
    container_name: ros2_discovery
    command: bash -c "source /opt/ros/humble/setup.bash &&
                        fastdds discovery --server-id 0"

