x-common: &common
  env_file:
    - .env
  volumes:
    - ./fastrtps.xml:/fastrtps.xml
    - /dev:/dev
    - ./ydlidar_launch.py:/ros2_ws/install/ydlidar_ros2_driver/share/ydlidar_ros2_driver/ydlidar_launch2.py
    - ./TG.yaml:/TG.yaml
  network_mode: host
  restart: unless-stopped

services:
  ros2_lidar:
    <<: *common
    build: .
    privileged: true
    command: >
      bash -c "source /opt/ros/humble/setup.bash &&
               source /ros2_ws/install/setup.bash &&
               ros2 launch ydlidar_ros2_driver ydlidar_launch2.py"
